version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.14
    steps:
      - checkout
      - run:
          name: Installing...
          command: yarn install
      - run:
          name: Building...
          command: yarn build
